#+STARTUP: overview
#+TITLE: Mail Configuration
#+AUTHOR: Diamond Bond
#+LANGUAGE: en
#+OPTIONS: num:nil
#+PROPERTY: header-args :mkdirp yes :tangle yes :results silent :noweb yes
#+auto_tangle: t

* Header
Enable lexical binding.
#+begin_src emacs-lisp
  ;;; mail.el --- Mail Configuration. -*- lexical-binding: t; -*-

  ;; Copyright (C) 2022 Diamond Bond
  ;; This file is NOT part of GNU Emacs.
  ;; This file is free software.

  ;; Author: Diamond Bond <diamondbond1@gmail.com>
  ;; URL: https://github.com/diamondbond/emacs
  ;; Package-Requires: ((emacs "28.1"))

  ;;; Commentary:
  ;; This file provides the user configuration.

  ;;; Code:

#+end_src

* Introduction

URL: https://github.com/DiamondBond/emacs/blob/master/modules/mail.org

/mu4e/ (/mu/) & /offlineimap/ to manage Email within Emacs.

/mu/ is the server.

/mu4e/ is the mail client within Emacs.

/offlineimap/ is the imap synchronization utility.

Make sure you store your gmail app specific passwords in ~/.emacs.d/authinfo.gpg.

mu4e and mu can be automatically compiled and installed with the defuns below in =functions=.
There is no need to install either of these packages with your package manager, Emacs can handle the mail server components for you.

#+begin_quote
  M-x mu-setup/automagic
#+end_quote

NOTE: You'll need to comb through this document and replace all instances of my Email address with yours and my file-paths with your respective file-paths.

** Sources

https://blog.leonardotamiano.xyz/posts/mu4e-setup/#part-2-configuring-mu4e
https://f-santos.gitlab.io/2020-04-24-mu4e.html
http://cachestocaches.com/2017/3/complete-guide-email-emacs-using-mu-and-/

* Installation

** 0. Prerequisites

*** 0.1 maildir
Create your maildir in $HOME as ~/mail

#+begin_src sh :tangle no
  mkdir -p ~/mail
#+end_src

*** 0.2 offlineimap

#+begin_src sh :tangle no
  yay -S offlineimap
#+end_src

** 1. Configuring offlineimap

~/[[https://github.com/DiamondBond/dotfiles/blob/master/.offlineimaprc][offlineimap.rc]]

[[https://github.com/DiamondBond/dotfiles/blob/master/.offlineimap.py][~/offlineimap.py]]

These files should be automatically tangled below.

** 2. Configuring mu

Scroll down to =Functions= to understand what these functions do, you'll have to change the maildir & my-address flags to correspond to your own maildir & address.

*** Automatically

Automatically build, install & run mu server/index.

#+begin_quote
M-x mu-setup/automagic
#+end_quote

*** Manually

**** Compile mu

Compile mu & mu4e.

#+begin_quote
M-x mu-setup/build-mu-binary
#+end_quote

**** Initialize mu

Initialize mu with maildir & address.

#+begin_quote
M-x mu-setup/init-mu
#+end_quote

**** Build mu index

Inform mu as to the contents of ~/mail by building/rebuilding the mu index.

#+begin_quote
M-x mu-setup/rebuild-mu-index
#+end_quote

* Declaration
** Configuration Files

These files will get automatically tangled to their respective locations.

*** =~/.offlineimaprc=
#+begin_src conf :tangle ~/.offlineimaprc
  [general]
  accounts = Gmail
  maxsyncaccounts = 1
  pythonfile = ~/.offlineimap.py

  [Account Gmail]
  localrepository = Local
  remoterepository = Remote

  [Repository Local]
  type = Maildir
  localfolders = ~/mail

  [Repository Remote]
  type = Gmail
  remoteuser = diamondbond1@gmail.com
  remotepasseval = get_password_emacs("imap.gmail.com", "diamondbond1@gmail.com", "993")
  realdelete = no

  folderfilter = lambda foldername: foldername not in ['[Gmail]/Spam', '[Gmail]/All Mail', '[Gmail]/Starred', '[Gmail]/Important']

  holdconnectionopen = true
  keepalive = 60
  sslcacertfile = /etc/ssl/certs/ca-certificates.crt
#+end_src

*** =~/.offlineimap.py=
#+begin_src python :tangle ~/.offlineimap.py
  #!/usr/bin/python
  import re, os

  def get_password_emacs(machine, login, port):
	  s = "machine %s login %s port %s password ([^ ]*)\n" % (machine, login, port)
	  p = re.compile(s)
	  authinfo = os.popen("gpg -q --no-tty -d ~/.authinfo.gpg").read()
	  return p.search(authinfo).group(1)
#+end_src
** Functions
*** 1. Compile mu

'mu' binary is output to ~/.emacs.d/straight/repos/mu/build/mu/mu

#+begin_src emacs-lisp
  (defun mu-setup/build-mu-binary ()
	"Compiles 'mu' binary."
	(interactive)
	(async-shell-command "cd ~/.emacs.d/straight/repos/mu; ./autogen.sh; ninja -C build"))
#+end_src

*** 2. Initialize mu

NOTE: Modify this defun to contain your =maildir= & email address.

#+begin_src emacs-lisp
  (defun mu-setup/init-mu ()
	"Initialize 'mu' db."
	(interactive)
	(async-shell-command "~/.emacs.d/straight/repos/mu/build/mu/mu init --maildir=~/mail/ --my-address=diamondbond1@gmail.com"))
#+end_src

*** 3. Rebuild mu index.
#+begin_src emacs-lisp
  (defun mu-setup/rebuild-mu-index ()
	"Rebuilds 'mu' index."
	(interactive)
	(async-shell-command "~/.emacs.d/straight/repos/mu/build/mu/mu index"))
#+end_src
*** 4. Automagic setup
#+begin_src emacs-lisp
  (defun mu-setup/automagic ()
	"Auto-magically configures 'mu'."
	(interactive)
	(mu-setup/build-mu-binary)
	(sit-for 5)
	(mu-setup/init-mu)
    (sit-for 5)
	(mu-setup/rebuild-mu-index))
#+end_src
*** =sync/mail=
Sync Email to local mail directory.
#+begin_src emacs-lisp
  (defun sync/mail ()
	"Sync email."
	(interactive)
	(async-shell-command "offlineimap")
	(mu4e-update-index))
#+end_src
** Use-package
*** Initialize =mu4e=
**** Description
mu4e mail client.
**** Code
#+begin_src emacs-lisp
  (use-package mu4e
	:straight ( :host github
				:repo "djcb/mu"
				:branch "master"
				:files ("build/mu4e/*")
				:pre-build (("./autogen.sh") ("make")))
	:custom   (mu4e-mu-binary (expand-file-name "build/mu/mu" (straight--repos-dir "mu")))
	:config
	;; default
	(require 'org-mu4e)
	(setq mu4e-maildir (expand-file-name "~/mail"))

	;; set folders
	(setq mu4e-drafts-folder "/[Gmail].Drafts")
	(setq mu4e-sent-folder   "/[Gmail].Sent Mail")
	(setq mu4e-trash-folder  "/[Gmail].Trash")

	;; don't save message to Sent Messages, GMail/IMAP will take care of this
	(setq mu4e-sent-messages-behavior 'delete)

	;; composing mail
	(setq mu4e-compose-dont-reply-to-self t)

	;; don't keep message buffers around
	(setq message-kill-buffer-on-exit t)

	;; display options
	(setq mu4e-view-show-images t)
	(setq mu4e-view-show-addresses 't)

	;; make sure that moving a message (like to Trash) causes the
	;; message to get a new file name.  This helps to avoid the
	;; dreaded "UID is N beyond highest assigned" error.
	;; See this link for more info: https://stackoverflow.com/a/43461973
	(setq mu4e-change-filenames-when-moving t)

	;; setup some handy shortcuts
	(setq mu4e-maildir-shortcuts
		  '(("/INBOX"             . ?i)
			("/[Gmail].Sent Mail" . ?s)
			("/[Gmail].Trash"     . ?t)))

	;; attachments go here
	(setq mu4e-attachment-dir  "~/mail/attachments")

	;; modify behavior when putting something in the trash (T flag) so as
	;; to make it sync to the remote server. This code deals with the bug
	;; that, whenever a message is marked with the trash label T,
	;; offlineimap wont sync it back to the gmail servers.
	;;
	;; NOTE: Taken from
	;; http://cachestocaches.com/2017/3/complete-guide-email-emacs-using-mu-and-/
	(defun remove-nth-element (nth list)
	  (if (zerop nth) (cdr list)
		(let ((last (nthcdr (1- nth) list)))
		  (setcdr last (cddr last))
		  list)))
	(setq mu4e-marks (remove-nth-element 5 mu4e-marks))
	(add-to-list 'mu4e-marks
				 '(trash
				   :char ("d" . "▼")
				   :prompt "dtrash"
				   :dyn-target (lambda (target msg) (mu4e-get-trash-folder msg))
				   :action (lambda (docid msg target)
							 (mu4e~proc-move docid
											 (mu4e~mark-check-target target) "-N"))))

	;; inbox-query
	(setq db/mu4e-inbox-query
		  "(maildir:/Inbox OR maildir:/INBOX) AND flag:unread")

	;; go-to-inbox function
	(defun db/go-to-inbox ()
	  "View unread inbox."
	  (interactive)
	  (mu4e-headers-search db/mu4e-inbox-query))

	;; allow for updating mail using 'U' in the main view:
	(setq mu4e-get-mail-command "offlineimap")

	;; why would I want to leave my message open after I've sent it?
	(setq message-kill-buffer-on-exit t)
	;; don't ask for a 'context' upon opening mu4e
	(setq mu4e-context-policy 'pick-first)
	;; don't ask to quit
	(setq mu4e-confirm-quit nil)

	;; define z-map keybind
	(define-key z-map (kbd "M") 'mu4e)

	;; start mu4e
	(mu4e t))
#+end_src
*** Initialize =mu4e-alert=
**** Description
Show alerts for unread emails.
**** Code
#+begin_src emacs-lisp
  (use-package mu4e-alert
	:straight t
	:init
	(defun db/mu4e-notif ()
	  "Display both mode line and desktop alerts for incoming new emails."
	  (interactive)
	  (mu4e-update-mail-and-index 1)        ; getting new emails is ran in the background
	  (mu4e-alert-enable-mode-line-display) ; display new emails in mode-line
	  (mu4e-alert-enable-notifications))    ; enable desktop notifications for new emails
	(defun db/mu4e-refresh ()
	  "Refresh emails every 300 seconds and display desktop alerts."
	  (interactive)
	  (mu4e t)                            ; start silently mu4e (mandatory for mu>=1.3.8)
	  (run-with-timer 0 300 'db/mu4e-notif))
	:after mu4e
	:bind ("<f2>" . db/mu4e-refresh)  ; F2 turns Emacs into a mail client
	:config

	;; show unread emails from all inboxes
	(setq mu4e-alert-interesting-mail-query db/mu4e-inbox-query)

	;; show notifications for mails already notified
	(setq mu4e-alert-notify-repeated-mails nil)

	;; mode line alerts:
	(add-hook 'after-init-hook #'mu4e-alert-enable-mode-line-display)

	;; desktop alerts
	(mu4e-alert-set-default-style 'libnotify)
	;; auto-enable notifications when opening mu4e
	(add-hook 'after-init-hook #'mu4e-alert-enable-notifications)

	;; enable notifications
	(mu4e-alert-enable-notifications))
#+end_src
*** Initialize =smtpmail=
**** Description
smtp mail within Emacs.
**** Code
#+begin_src emacs-lisp
  (use-package smtpmail
	:straight t
	:config
	(setq message-send-mail-function 'smtpmail-send-it
		  starttls-use-gnutls t
		  smtpmail-starttls-credentials
		  '(("smtp.gmail.com" 587 nil nil))
		  smtpmail-auth-credentials
		  (expand-file-name "~/.authinfo.gpg")
		  smtpmail-default-smtp-server "smtp.gmail.com"
		  smtpmail-smtp-server "smtp.gmail.com"
		  smtpmail-smtp-service 587
		  smtpmail-debug-info t))
#+end_src

* Footer
#+begin_src emacs-lisp

  (provide 'mail)
  ;;; mail.el ends here
#+end_src
