#+TITLE: Diamond's Emacs
#+AUTHOR: index
#+EMAIL: diamondbond1@gmail.com
#+LANGUAGE: en
#+CREATOR: Emacs 28.1 (Org mode 9.5.3)
#+OPTIONS: toc:2

* Introduction

[[https://diamondbond.neocities.org/emacs.html][The entire configuration can be viewed here in HTML format]].

* Installation

[[https://github.com/DiamondBond/emacs/blob/master/docs/emacsfromsource.org][Emacs build instructions]].

Clone this repo:

#+begin_src sh
  $ git clone https://github.com/diamondbond/emacs.git ~/.emacs.d --depth 1
#+end_src

[[https://github.com/DiamondBond/emacs/blob/master/bin/tangle.sh][Tangle]]:

#+begin_src sh
  $ cd ~/.emacs.d/bin
  $ ./tangle.sh
#+end_src

*NOTE:* Please run tangle.sh whenever you edit a =.org= configuration file.

** Icons

If you care about fancy icons, install the fonts provided by [[https://github.com/domtronn/all-the-icons.el][all the icons]]:

#+begin_src emacs-lisp
  M-x all-the-icons-install-fonts
#+end_src

*** Windows
[[https://github.com/domtronn/all-the-icons.el/archive/refs/heads/master.zip][Download]] & extract to C:\Windows\Fonts

** LSP

Most IDE-like features are provided by the [[https://github.com/emacs-lsp/lsp-mode][LSP]] package. For it to work properly, you need to install the appropriate [[https://github.com/emacs-lsp/lsp-mode#supported-languages][language servers]] although Emacs will prompt you to install them automatically upon encountering a file for that language.

** Email

Refer to the [[https://github.com/DiamondBond/emacs/blob/master/docs/setupemail.org][Email setup documentation]] for this functionality.

** Dependencies

Refer to the [[https://github.com/DiamondBond/emacs/blob/master/docs/dependencies.org][Dependencies documentation]].

*** Windows

Refer to the *WIP* [[https://github.com/DiamondBond/emacs/blob/master/docs/emacsonwin.org][Windows Dependencies documentation]].

** Customization

Edit =.emacs.d/globals.org= to change the default username, email address, nicks & browser.

Edit =.emacs.d/userconfig.org= to add your custom settings and/or override base settings.

You may also edit =.emacs.d/config.org= directly, but your custom settings might be wiped out during an update.

* Usage

** Tangling

This Emacs configuration will auto-tangle all the related configuration .org files on save thanks to [[https://github.com/yilkalargaw/org-auto-tangle][org-auto-tangle]].

Add tangle.sh to your =$PATH= in your =~/.bashrc= file:

#+begin_src sh
  PATH="$HOME/.emacs.d/bin:$PATH"
#+end_src

Now you can run tangle.sh from anywhere.

I recommend adding this alias to your =~/.bash_aliases= file:

#+begin_src sh
  alias edaemon="tangle.sh && emacs --daemon"
#+end_src

This will tangle and start the Emacs daemon.

NOTE: call =tangle.sh= with an arbitrary argument to use [[https://github.com/DiamondBond/bin/blob/master/auth-restore.sh][M-x auth-restore]].

*** Windows
Run =tangle.bat= instead of =tangle.sh=.

** Running

Start Emacs with:

#+begin_src sh
  $ edaemon
#+end_src

Connect to the Emacs daemon via =emacsclient= with the following command:

#+begin_src sh
  $ emacsclient -c -n -a 'emacs'
#+end_src

*** Windows

Run =daemon.bat= and wait for the Emacs daemon to start then run =summon.bat= to summon a frame.

** Updating

Update this Emacs configuration and upgrade its packages with:

#+begin_src emacs-lisp
  M-x config/update
#+end_src

* Contributors

@wereket

* Thanks

Nicolas Rougier - CSS

Xah Lee - wolfram-mode & math-input-mode
