#+TITLE: Dependencies
#+LANGUAGE: en
#+OPTIONS: num:nil toc:2

Declarative dependency listing for this Emacs configuration.

NOTE: This is a WIP and some things may still be missing.

* Packages

** System

#+begin_quote
gcc make
cmake ninja
autoreconf
offlineimap
fzf ripgrep ag
clang clangd llvm
texlive-core texlive-bin texlive-science
imagemagick
editorconfig
libjansson
rust-all cargo
nodejs npm
libxml2
gopls
gnuplot
prettier
hunspell
python
java
jupyter-notebook
wolframengine wolframscript
wolframlanguageforjupyter
sbcl quicklisp
mpv
#+end_quote

For a complete list of system packages please view my [[https://github.com/DiamondBond/dotfiles/blob/master/pacman.txt][pacman manifest]].

** Python

We let lsp handle the python language server.

#+begin_src sh
  pip3 install pyflakes isort nose pytest pygifsicle nose2 httpserver future pandas numpy matplotlib python-rofi jupyter grip git-lines-graph
#+end_src

** NodeJS

Deno & typescript-language-server for Typescript (TS/TSX) support.

#+begin_src sh
  sudo npm install -g deno typescript-language-server bash-language-server
#+end_src

** Quicklisp
https://lisp-lang.org/learn/getting-started/

** Mu for mu4e
Will be autoinstalled by straight.el to =~/.emacs.d/straight/repos/mu/build/mu=.

* Files

** Userconfig

#+begin_quote
~/.emacs.d/userconfig.org

~/.emacs.d/globals.org

~/.emacs.d/custom.el
#+end_quote

** Auth Files

#+begin_quote
~/.authinfo.gpg

~/.secrets.el.gpg

~/.emacs.d/network-security.data
#+end_quote

** Dropbox Folders

Symlink ~/org & ~/pdf to their respective subdirs within ~/Dropbox.

#+begin_src sh
  mkdir -p ~/Dropbox/{org,pdfs}; ln -s ~/Dropbox/org ~/org; ln -s ~/Dropbox/pdfs ~/pdfs
#+end_src
