* How to compile and install Emacs

** Grabbing sources

Clone the latest Emacs@HEAD sources:

#+begin_src sh

  cd ~/git
  git clone -b master git://git.sv.gnu.org/emacs.git

#+end_src

Or alternatively download the [[https://www.gnu.org/software/emacs/download.html][latest Emacs stable release]].

** Configuring

Configure Emacs with native-comp, xinput2, imagemagick, harfbuzz, json, athena-toolkit with xaw3d-toolbars & custom O3 CFLAGS for mild performance improvements.

NOTE: If you are intending to compile Emacs<=29 then omit the =--with-xinput2= flag when running =./configure= below.

NOTE: that if you intend to run this emacs configuration for long periods of time then it is recommended to use the athena toolkit as its anecdotally more stabler (imo) as well as blessing you with the ability to not lose your emacs session upon logout - ie you can reconnect to your same emacs session after doing system updates (hopefully not kernel or systemd) and logging out and back in.

#+begin_src sh

  # Run the auto-generation script
  ./autogen.sh

  # Configure Emacs
  ./configure --with-dbus --with-gif --with-jpeg --with-png --with-rsvg --with-tiff --with-xft --with-xpm --with-gpm=no --disable-silent-rules --with-modules --with-file-notification=inotify --with-mailutils --with-x=yes --with-x-toolkit=athena --without-gconf --without-gsettings --with-lcms2 --with-imagemagick --with-xml2 --with-json --with-harfbuzz --without-compress-install --with-native-compilation --with-xinput2 CFLAGS="-O3 -mtune=native -march=native -fomit-frame-pointer -flto -fno-semantic-interposition"

#+end_src

** Compiling

Compile with n-1 cores and do native full ahead of time compilation.

#+begin_src sh

  make NATIVE_FULL_AOT=1 -j$(($(nproc)-1))


#+end_src

NOTE: This may take awhile.

** Installing

Finally install Emacs.

#+begin_src sh
  sudo make install
#+end_src
